### GET request to example server
POST http://localhost:8080/pipeline/47d2d663-e011-4cfc-ab94-314cfac6777c/execute/01

 {
    "linksz": [
      "http://localhost:3001/sum",
      "http://localhost:3001/avg",
      "http://localhost:3001/min",
      "http://localhost:3001/max"
    ]
  }
